//! `/api/v1/artwork/*` — shared artwork cache (Phase 1.h.1).
//!
//! Two surfaces split along the same auth-vs-public boundary as
//! streaming and share:
//!
//! - **Upload** (`POST /api/v1/artwork`): JWT-authed. Body is the
//!   raw image bytes (no multipart wrapper — keeps the path simple
//!   and Bytes-extractor-friendly). `Content-Type` must be one of
//!   `image/jpeg`, `image/png`, `image/webp`. Hash is computed
//!   server-side (BLAKE3 of the bytes) so the client can't tamper
//!   with the identity; a re-upload of the same content returns
//!   the same hash without re-writing. Caps at 4 MiB to keep the
//!   per-request memory footprint bounded — same ceiling the
//!   desktop's `metadata_artwork::MAX_BYTES` already enforces, so
//!   the two caches stay symmetric.
//! - **Public read** (`GET /api/v1/artwork/{hash}`): NOT behind the
//!   JWT middleware — the hash IS the credential, same model as
//!   the share token. 64 hex chars are validated at the boundary so
//!   `..` or `/` can't slip into the object_store key. Cache
//!   headers mark the response `immutable` since BLAKE3 makes
//!   re-fetching the same hash idempotent forever.
//!
//! Storage layout is flat (`artwork/<hash>` in object_store); the
//! MIME type lives in the `metadata_artwork` row alongside the
//! original byte size, so the GET handler vends the right
//! Content-Type without round-tripping the store for a HEAD.
//!
//! Both routes answer 503 when storage isn't configured (env
//! `WAVEFLOW_ARTWORK_LOCAL_DIR` unset) — same opt-in shape as the
//! streaming surface, so a deploy that doesn't want the feature
//! just leaves the var off.

use axum::{
    body::Bytes,
    extract::{DefaultBodyLimit, Path, State},
    http::{header, HeaderMap, HeaderValue, StatusCode},
    response::{IntoResponse, Response},
    Extension, Json,
};
use serde::Serialize;
use utoipa::ToSchema;
use utoipa_axum::{router::OpenApiRouter, routes};

use crate::{
    artwork_pipeline::{self, PipelineError, VariantKind},
    middleware::UserId,
    storage::StorageError,
    AppState,
};

/// Hard cap on a single artwork upload. 4 MiB matches the desktop's
/// `metadata_artwork::MAX_BYTES`, which in turn was sized for
/// Deezer's `picture_xl` (~200 KB) with comfortable headroom for
/// arbitrary user uploads (album scans, scanned vinyl sleeves) once
/// the artwork pipeline ships in 1.h.3.
const MAX_UPLOAD_BYTES: usize = 4 * 1024 * 1024;

/// Accepted MIME types. Each is byte-perfect-streamable straight
/// from object_store with the recorded Content-Type — no
/// re-encoding in 1.h.1. PNG is included up front because it's the
/// common pasteboard format on Linux desktops; WebP because modern
/// cover-art services already vend it and re-encoding to JPEG would
/// lose alpha + waste bytes.
const ACCEPTED_MIMES: &[&str] = &["image/jpeg", "image/png", "image/webp"];

#[derive(Debug, Serialize, ToSchema)]
pub struct UploadResponse {
    /// BLAKE3 hex digest of the uploaded bytes — the row identity in
    /// `metadata_artwork` and the path segment for the public read.
    /// Stable for the lifetime of the cache; clients can persist
    /// this as a `cover_hash` / `picture_hash` reference.
    pub hash: String,
    /// Original byte count. Echoed back so the client doesn't have to
    /// re-measure the bytes they just sent.
    pub byte_size: i64,
    /// MIME type the server stored (mirrors the `Content-Type`
    /// header the client sent). Echoed back so a future client can
    /// learn the canonical normalisation (e.g. if we ever map
    /// `image/jpg` → `image/jpeg`).
    pub mime: String,
    /// Path-relative URL the bytes are served at. Combine with the
    /// origin to fetch — kept relative because the server doesn't
    /// know the public origin in a reverse-proxied deploy.
    pub url: String,
    /// Variants generated by the resize pipeline (Phase 1.h.3).
    /// Always two entries today (`thumb`, `preview`) in alphabetical
    /// order. A client that doesn't need the smaller sizes can
    /// ignore the field; one that does avoids a second GET.
    pub variants: Vec<VariantResponse>,
}

/// Per-variant projection of the resize pipeline's output. Mirrors
/// `metadata_artwork_variant` so a client can pre-size the layout
/// slot before fetching the bytes.
#[derive(Debug, Serialize, ToSchema)]
pub struct VariantResponse {
    /// `thumb` | `preview`. New buckets land here as the SQL CHECK
    /// list grows; clients should treat unknown values as
    /// fall-through to the parent (no resize available).
    pub variant: String,
    /// BLAKE3 hex of the re-encoded variant bytes.
    pub hash: String,
    pub mime: String,
    pub byte_size: i64,
    pub width: i32,
    pub height: i32,
    /// `/api/v1/artwork/{parent}/{variant}` — the suffixed read.
    /// A client that cached the variant hash can also hit
    /// `/api/v1/artwork/{variant_hash}` directly (the parent GET
    /// also resolves variant hashes).
    pub url: String,
}

pub fn auth_router(state: AppState) -> OpenApiRouter {
    // Raise the default axum body limit above our 4 MiB cap so the
    // handler's `body.len() > MAX_UPLOAD_BYTES` check is the
    // authoritative gatekeeper. Without this, axum 0.8's default
    // 2 MiB limit short-circuits the request to 413 before the
    // handler runs — which is technically correct but hides our
    // "exactly 4 MiB allowed" contract. The +1 KiB of slack lets a
    // borderline 4 MiB upload reach the handler so the boundary
    // case lands on our error variant (and the matching test
    // observes a real, handler-issued 413).
    OpenApiRouter::new()
        .routes(routes!(upload_artwork))
        .layer(DefaultBodyLimit::max(MAX_UPLOAD_BYTES + 1024))
        .with_state(state)
}

pub fn public_router(state: AppState) -> OpenApiRouter {
    OpenApiRouter::new()
        .routes(routes!(get_artwork))
        .routes(routes!(get_artwork_variant))
        .with_state(state)
}

/// Upload an artwork file. Body is raw image bytes (no multipart),
/// `Content-Type` MUST be one of `image/jpeg`, `image/png`,
/// `image/webp`. Idempotent — re-uploading the same content returns
/// the same hash and skips the storage write.
///
/// Responses:
/// - 200: `{ hash, byte_size, mime, url }`
/// - 400: missing or unsupported Content-Type, empty body
/// - 401: missing or invalid bearer
/// - 413: body exceeded 4 MiB cap
/// - 503: artwork storage disabled at boot
#[utoipa::path(
    post,
    path = "/api/v1/artwork",
    tag = "artwork",
    params(
        ("authorization" = String, Header, description = "Bearer JWT issued by Better Auth"),
        ("content-type" = String, Header, description = "image/jpeg | image/png | image/webp"),
    ),
    request_body(
        content_type = "image/jpeg",
        description = "Raw image bytes. Capped at 4 MiB.",
    ),
    responses(
        (status = 200, description = "Bytes accepted (or already cached)", body = UploadResponse),
        (status = 400, description = "Unsupported MIME, empty body, or other client-side validation failure"),
        (status = 401, description = "Missing or invalid bearer token"),
        (status = 413, description = "Body exceeded 4 MiB cap"),
        (status = 500, description = "Storage or database failure"),
        (status = 503, description = "Artwork storage disabled at boot"),
    ),
)]
async fn upload_artwork(
    State(state): State<AppState>,
    // `_user_id` is unused today — uploads aren't tenant-scoped
    // because the artwork cache is dedup'd across the whole
    // deployment by BLAKE3 hash. The Extension binding is still
    // present so the middleware's auth check runs (you only reach
    // this handler with a valid Bearer), and so future per-user
    // quotas can hook in here without an API change.
    Extension(UserId(_user_id)): Extension<UserId>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Response, ArtworkError> {
    let storage = state.artwork.as_ref().ok_or(ArtworkError::Disabled)?;

    if body.is_empty() {
        return Err(ArtworkError::EmptyBody);
    }
    if body.len() > MAX_UPLOAD_BYTES {
        return Err(ArtworkError::TooLarge);
    }

    let mime = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        // `Content-Type: image/jpeg; charset=binary` shouldn't be
        // rejected over a parameter we don't care about — split on
        // ';' and trim, then compare the bare media type.
        .map(|s| s.split(';').next().unwrap_or(s).trim().to_ascii_lowercase())
        .ok_or(ArtworkError::UnsupportedMime)?;
    if !ACCEPTED_MIMES.contains(&mime.as_str()) {
        return Err(ArtworkError::UnsupportedMime);
    }

    let hash = blake3::hash(body.as_ref()).to_hex().to_string();
    let byte_size = i64::try_from(body.len()).expect("4 MiB cap fits in i64");

    // Ordering: bytes first, row second. A racing GET that sees the
    // row knows the bytes are already committed (storage.put has
    // returned); a GET that arrives between bytes-written and row-
    // inserted simply 404s on the meta lookup and the client retries.
    // The reverse order would race a GET against the brief window
    // where the row exists but the storage put hasn't returned yet,
    // producing a 500 instead of a clean 404.
    //
    // Optimisation: skip the storage write if the metadata row
    // already exists. A re-upload of the same bytes is a no-op then,
    // saving a backend round-trip in the common case (the desktop
    // bundles cover bytes with sync ops and would otherwise re-send
    // every cached cover on each sync).
    if let Some(existing) = crate::db::artwork::fetch_meta(&state.db, &hash)
        .await
        .map_err(ArtworkError::Db)?
    {
        // Echo the stored row, not the incoming request: BLAKE3
        // collision-resistance means `byte_size` is identical
        // either way, but `mime` could diverge under a future
        // canonicalisation (the DTO already advertises this
        // contract — see `UploadResponse::mime`), and reading
        // through the row is what makes the documented behaviour
        // unconditionally true.
        let existing_variants = crate::db::artwork::fetch_variants_for_parent(&state.db, &hash)
            .await
            .map_err(ArtworkError::Db)?;
        return Ok((
            StatusCode::OK,
            Json(UploadResponse {
                hash: hash.clone(),
                byte_size: existing.byte_size,
                mime: existing.mime,
                url: format!("/api/v1/artwork/{hash}"),
                variants: existing_variants
                    .into_iter()
                    .map(|(variant, meta)| VariantResponse {
                        url: format!("/api/v1/artwork/{hash}/{variant}"),
                        variant,
                        hash: meta.hash,
                        mime: meta.mime,
                        byte_size: meta.byte_size,
                        width: meta.width,
                        height: meta.height,
                    })
                    .collect(),
            }),
        )
            .into_response());
    }

    // Run the resize pipeline BEFORE touching storage — a malformed
    // image surfaces as 400 here, so we never write half-bytes the
    // GET path would then have to clean up. Pipeline failures map to
    // either 400 (client gave us garbage) or 500 (encoder failed on
    // valid input).
    let variants =
        artwork_pipeline::generate_variants(body.as_ref()).map_err(ArtworkError::from_pipeline)?;

    storage
        .put(&hash, body)
        .await
        .map_err(ArtworkError::Storage)?;

    // Race-safe: another concurrent upload of the same bytes may
    // have inserted the row between our `fetch_meta` and `put`.
    // `insert_if_absent` collapses the duplicate via
    // `ON CONFLICT DO NOTHING` and we treat both outcomes (we won,
    // we lost) as success — the bytes are now durably stored either
    // way.
    let _new_row = crate::db::artwork::insert_if_absent(&state.db, &hash, &mime, byte_size)
        .await
        .map_err(ArtworkError::Db)?;

    // Write each variant: bytes to object_store, then row to
    // `metadata_artwork_variant`. Same ordering as the parent (bytes
    // first, row second) so a racing GET can't observe a row with
    // missing bytes.
    let mut variant_responses = Vec::with_capacity(variants.len());
    for variant in variants {
        storage
            .put(&variant.hash, variant.bytes.clone())
            .await
            .map_err(ArtworkError::Storage)?;
        crate::db::artwork::insert_variant_if_absent(
            &state.db,
            &hash,
            variant.kind.as_str(),
            &variant.hash,
            variant.mime,
            variant.byte_size,
            variant.width as i32,
            variant.height as i32,
        )
        .await
        .map_err(ArtworkError::Db)?;
        variant_responses.push(VariantResponse {
            variant: variant.kind.as_str().to_string(),
            url: format!("/api/v1/artwork/{}/{}", hash, variant.kind.as_str()),
            hash: variant.hash,
            mime: variant.mime.to_string(),
            byte_size: variant.byte_size,
            width: variant.width as i32,
            height: variant.height as i32,
        });
    }

    Ok((
        StatusCode::OK,
        Json(UploadResponse {
            hash: hash.clone(),
            byte_size,
            mime,
            url: format!("/api/v1/artwork/{hash}"),
            variants: variant_responses,
        }),
    )
        .into_response())
}

/// Fetch artwork bytes by hash. Public — no JWT, the 64-hex hash
/// IS the credential (same model as `share` tokens).
///
/// Responses:
/// - 200: image bytes with the original Content-Type
/// - 400: malformed hash (wrong length / non-hex)
/// - 404: no row matches
/// - 503: artwork storage disabled at boot
#[utoipa::path(
    get,
    path = "/api/v1/artwork/{hash}",
    tag = "artwork",
    params(
        ("hash" = String, Path, description = "BLAKE3 hex digest of the bytes (64 lowercase hex chars)"),
    ),
    responses(
        (status = 200, description = "Image bytes", content_type = "image/jpeg"),
        (status = 400, description = "Malformed hash"),
        (status = 404, description = "No artwork stored under this hash"),
        (status = 503, description = "Artwork storage disabled at boot"),
    ),
)]
async fn get_artwork(
    State(state): State<AppState>,
    Path(hash): Path<String>,
) -> Result<Response, ArtworkError> {
    let storage = state.artwork.as_ref().ok_or(ArtworkError::Disabled)?;

    if !crate::storage::is_well_shaped_hash(&hash) {
        return Err(ArtworkError::MalformedHash);
    }

    // Metadata lookup first — cheap (covered by PK) and tells us the
    // MIME type for the response. A miss here short-circuits the
    // storage call so we never log a backend NotFound for a hash that
    // was never registered. Falls back to the variant table so a
    // client that cached a variant hash can hit this same route
    // directly (the variant URLs in `UploadResponse.variants` advertise
    // a `/{parent}/{variant}` shape, but the raw hash also resolves
    // — useful when the client persists only the hash).
    let meta = match crate::db::artwork::fetch_meta(&state.db, &hash)
        .await
        .map_err(ArtworkError::Db)?
    {
        Some(meta) => meta,
        None => crate::db::artwork::fetch_meta_by_variant_hash(&state.db, &hash)
            .await
            .map_err(ArtworkError::Db)?
            .ok_or(ArtworkError::NotFound)?,
    };

    let bytes = storage.get(&hash).await.map_err(|err| match err {
        StorageError::NotFound => ArtworkError::NotFound,
        StorageError::Backend(e) => ArtworkError::Storage(StorageError::Backend(e)),
    })?;

    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_str(&meta.mime)
            .unwrap_or_else(|_| HeaderValue::from_static("application/octet-stream")),
    );
    headers.insert(header::CONTENT_LENGTH, HeaderValue::from(bytes.len()));
    // BLAKE3-keyed assets are immutable by construction: the hash
    // changes if the bytes change. `immutable` lets browsers skip the
    // revalidation on reload; 1y is the conventional "forever" ceiling
    // for HTTP caches.
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=31536000, immutable"),
    );
    // ETag = the hash itself. Lets a CDN dedupe across regions and
    // a client honour `If-None-Match` for a cheap revalidate.
    headers.insert(
        header::ETAG,
        HeaderValue::from_str(&format!("\"{}\"", meta.hash))
            .unwrap_or_else(|_| HeaderValue::from_static("\"artwork\"")),
    );

    Ok((StatusCode::OK, headers, bytes).into_response())
}

/// Fetch the bytes of one resize variant. Path is
/// `/api/v1/artwork/{parent}/{variant}` — the parent hash is the
/// upload hash, the variant suffix is `thumb` | `preview`. Mirrors
/// `get_artwork`'s cache + ETag posture (variants are immutable too,
/// the hash changes if the bytes change).
#[utoipa::path(
    get,
    path = "/api/v1/artwork/{hash}/{variant}",
    tag = "artwork",
    params(
        ("hash" = String, Path, description = "BLAKE3 hex of the PARENT (original) bytes"),
        ("variant" = String, Path, description = "Resize bucket: thumb | preview"),
    ),
    responses(
        (status = 200, description = "Variant bytes (JPEG)", content_type = "image/jpeg"),
        (status = 400, description = "Malformed parent hash or unknown variant"),
        (status = 404, description = "Parent or variant not stored"),
        (status = 503, description = "Artwork storage disabled at boot"),
    ),
)]
async fn get_artwork_variant(
    State(state): State<AppState>,
    Path((hash, variant)): Path<(String, String)>,
) -> Result<Response, ArtworkError> {
    let storage = state.artwork.as_ref().ok_or(ArtworkError::Disabled)?;

    if !crate::storage::is_well_shaped_hash(&hash) {
        return Err(ArtworkError::MalformedHash);
    }
    // Validate the variant suffix at the boundary so an unknown
    // value gets a clean 400 instead of slipping through to a
    // table miss + 404.
    if VariantKind::parse(&variant).is_none() {
        return Err(ArtworkError::UnknownVariant);
    }

    let meta = crate::db::artwork::fetch_variant(&state.db, &hash, &variant)
        .await
        .map_err(ArtworkError::Db)?
        .ok_or(ArtworkError::NotFound)?;

    // Variant bytes are stored under their OWN hash in object_store
    // — same layout as the parent. The metadata row supplies the
    // resolved hash + MIME + size; we just fetch + serve.
    let bytes = storage.get(&meta.hash).await.map_err(|err| match err {
        StorageError::NotFound => ArtworkError::NotFound,
        StorageError::Backend(e) => ArtworkError::Storage(StorageError::Backend(e)),
    })?;

    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_str(&meta.mime)
            .unwrap_or_else(|_| HeaderValue::from_static("image/jpeg")),
    );
    headers.insert(header::CONTENT_LENGTH, HeaderValue::from(bytes.len()));
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=31536000, immutable"),
    );
    headers.insert(
        header::ETAG,
        HeaderValue::from_str(&format!("\"{}\"", meta.hash))
            .unwrap_or_else(|_| HeaderValue::from_static("\"artwork-variant\"")),
    );

    Ok((StatusCode::OK, headers, bytes).into_response())
}

/// Local error type so each variant maps to its own status code in
/// a single `IntoResponse` impl. Keeps the handler bodies free of
/// the match-on-status-code boilerplate.
#[derive(Debug)]
enum ArtworkError {
    Disabled,
    EmptyBody,
    TooLarge,
    UnsupportedMime,
    MalformedHash,
    UnknownVariant,
    InvalidImage,
    EncodeFailed,
    NotFound,
    Storage(StorageError),
    Db(sqlx::Error),
}

impl ArtworkError {
    /// Map a pipeline failure to the right HTTP-shaped variant.
    /// Decode + zero-dimension are client-side problems (the bytes
    /// they sent weren't a supported image); encode is a server-side
    /// problem (our JPEG encoder bailed on otherwise valid input).
    fn from_pipeline(err: PipelineError) -> Self {
        match err {
            PipelineError::EmptySource | PipelineError::ZeroDimension => Self::InvalidImage,
            PipelineError::Decode(decode_err) => {
                tracing::warn!(error = %decode_err, "artwork upload rejected: decode failed");
                Self::InvalidImage
            }
            PipelineError::Encode(encode_err) => {
                tracing::error!(error = %encode_err, "artwork variant encode failed");
                Self::EncodeFailed
            }
        }
    }
}

impl IntoResponse for ArtworkError {
    fn into_response(self) -> Response {
        match self {
            Self::Disabled => (
                StatusCode::SERVICE_UNAVAILABLE,
                "artwork storage disabled at boot",
            )
                .into_response(),
            Self::EmptyBody => (StatusCode::BAD_REQUEST, "empty body").into_response(),
            Self::TooLarge => (StatusCode::PAYLOAD_TOO_LARGE, "body exceeds 4 MiB").into_response(),
            Self::UnsupportedMime => (
                StatusCode::BAD_REQUEST,
                "Content-Type must be image/jpeg, image/png, or image/webp",
            )
                .into_response(),
            Self::MalformedHash => (
                StatusCode::BAD_REQUEST,
                "hash must be 64 lowercase hex characters",
            )
                .into_response(),
            Self::UnknownVariant => (
                StatusCode::BAD_REQUEST,
                "variant must be one of: thumb, preview",
            )
                .into_response(),
            Self::InvalidImage => (
                StatusCode::BAD_REQUEST,
                "could not decode the uploaded bytes as JPEG / PNG / WebP",
            )
                .into_response(),
            Self::EncodeFailed => (
                StatusCode::INTERNAL_SERVER_ERROR,
                "failed to encode resize variant",
            )
                .into_response(),
            Self::NotFound => (StatusCode::NOT_FOUND, "artwork not found").into_response(),
            Self::Storage(err) => {
                tracing::error!(error = %err, "artwork storage call failed");
                (StatusCode::INTERNAL_SERVER_ERROR, "storage error").into_response()
            }
            Self::Db(err) => {
                tracing::error!(error = %err, "artwork db call failed");
                (StatusCode::INTERNAL_SERVER_ERROR, "database error").into_response()
            }
        }
    }
}
