// Flat-config ESLint (v9+). Keeps the rules tight on the React + TS
// surface and ignores the codegen + build outputs. Prettier owns
// whitespace; ESLint owns semantics.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'

export default tseslint.config(
  {
    // `routeTree.gen.ts` is regenerated by the TanStack Router Vite
    // plugin on every dev start — linting it would surface autogen
    // noise that we have no control over.
    ignores: ['dist/**', '.output/**', '.nitro/**', '.tanstack/**', 'src/routeTree.gen.ts'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // CommonJS config files (`.commitlintrc.cjs`, etc.) — apply the
    // node globals so `module` / `require` aren't `no-undef`.
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    settings: {
      react: { version: '19.2' },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // React 17+ runtime — explicit React imports aren't required.
      'react/react-in-jsx-scope': 'off',
      // TanStack Router uses `Route = createFileRoute(...)({ ... })`
      // where the const isn't used directly — the plugin reads it
      // off the file. Tighten this once we have a custom rule for
      // those exports.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
)
